routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('mailable', function () {
    $tareaPendiente = App\TareaPendiente::find(13);

    return new App\Mail\NotificacionTareaPendiente($tareaPendiente);
});

// Auth
Route::get("login", "Auth\LoginController@showLoginForm")->name("login");
Route::post("login", "Auth\LoginController@login");
Route::post("logout", "Auth\LoginController@logout")->name("logout");

// Cuenta
Route::get("cuenta", "UsuarioController@detalles")->name("cuenta.detalles");
Route::post("cuenta", "UsuarioController@modificar");
Route::get("cuenta/cambiar-password", "UsuarioController@formularioPassword")->name("cuenta.cambiar-password");
Route::post("cuenta/cambiar-password", "UsuarioController@cambiarPassword");

// Inicio
Route::get("/", "InicioController@index")->name("inicio");

// Choferes
Route::resource("choferes", "ChoferesController")->except(["edit"]);

// Proveedores
Route::resource("proveedores", "ProveedoresController")->except(["edit"]);

// Vehiculos
Route::resource("vehiculos", "VehiculosController")->except(["edit"]);
Route::get("vehiculos/{id}/registrar-kilometraje", "VehiculosController@formularioRegistrarKms")->name("vehiculos.registrar-kilometraje");
Route::post("vehiculos/{id}/registrar-kilometraje", "VehiculosController@registrarKms");

// Trabajos de vehiculos
Route::resource("trabajos-vehiculos", "TrabajosVehiculosController")->except(["edit", "destroy"]);

// Alquileres
Route::get("alquileres/registrar", "AlquileresController@create")->name("alquileres.create");
Route::resource("alquileres", "AlquileresController")->except(["create", "edit", "destroy"]);

Route::post("alquileres/{id}/terminar", "AlquileresController@terminar")->name("alquileres.terminar");
Route::get("alquileres/{id}/registrar-pago", "AlquileresController@formularioRegistrarPago")->name("alquileres.registrar-pago");
Route::post("alquileres/{id}/registrar-pago", "AlquileresController@registrarPago");

// Gastos adicionales
Route::resource("gastos-adicionales", "GastosAdicionalesController")->except(["edit", "destroy"]);

// Reportes
Route::get("reportes/balances", "ReportesController@mostrarBalances")->name("reportes.balances");
Route::get("reportes/vehiculos", "ReportesController@mostrarVehiculos")->name("reportes.vehiculos");
Route::get("reportes/choferes", "ReportesController@mostrarChoferes")->name("reportes.choferes");

app/Http/Controllers/AlquileresController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CrearAlquiler;
use App\Alquiler;
use App\Chofer;
use App\Vehiculo;
use Carbon\Carbon;
use App\Http\Filters\FiltrosAlquileres;


class AlquileresController extends AdminPanelBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(FiltrosAlquileres $filtros)
    {
        $alquileres = Alquiler::with(["chofer", "vehiculo"])->filter($filtros)->paginate(15);

        return view("alquileres.index")->with([
            "vehiculos" => Vehiculo::nombreAsc()->get(),
            "alquileres" => $alquileres
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view("alquileres.create")->with([
            "choferesDisponibles" => Chofer::disponibles()->get(),
            "vehiculosDisponibles" => Vehiculo::disponibles()->get(),
        ]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CrearAlquiler $request)
    {

        
        $alquiler = new Alquiler();

        $alquiler->fill($request->except([
            "alquiler_indefinido",
            "descuento_semanal"
        ]));

        $alquiler->fill([
            "estado" => Alquiler::ESTADO_EN_CURSO,
            "fecha_inicio" => Carbon::today(),
            "descuento_semanal" => $request->has("descuento_semanal")
        ]);

        $alquiler->save();


        $chofer = Chofer::findOrFail($request->id_chofer);
        $chofer->asignarAlquilerActual($alquiler->id);

        $vehiculo = Vehiculo::findOrFail($request->id_vehiculo);
        $vehiculo->asignarAlquilerActual($alquiler->id);


        return redirect()->route("alquileres.index");
    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $alquiler = Alquiler::with(["chofer", "vehiculo"])->findOrFail($id);
        $movimientos = $alquiler->movimientosSaldo()->fechaDesc()->get();

        return view("alquileres.show")->with([
            "alquiler" => $alquiler,
            "ingresos" => $alquiler->calcularIngresosTotales(),
            "movimientosSaldo" => $movimientos
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(["notas" => "nullable|max:200"]);

        $alquiler = Alquiler::findOrFail($id);

        $alquiler->notas = $request->notas;
        $alquiler->save();

        return redirect()->route("alquileres.show", $alquiler->id);
    }


    /**
     * Terminar el alquiler
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function terminar(Request $request, $id)
    {
        
        $alquiler = Alquiler::findOrFail($id);

        if($alquiler->estaEnCurso()) {
            $alquiler->terminar();
        }

        return redirect()->route("alquileres.show", $alquiler->id);
    }



    /**
     * Mostrar formulario para registrar nuevo pago
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function formularioRegistrarPago(Request $request, $id)
    {
        $alquiler = Alquiler::findOrFail($id);

        if($alquiler->puedeRegistrarMovimientos()) {
            return view("alquileres.registrar-pago")->with("alquiler", $alquiler);
        }
        else {
            return redirect()->route("alquileres.show", $alquiler->id);
        }
        
    }


    /**
     * Registrar nuevo pago a un alquiler
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function registrarPago(Request $request, $id)
    {
        
        $request->validate([
            "fecha" => "required|date_format:d/m/Y|after_or_equal:-7day|before_or_equal:today",
            "tipo" => "required|in:pago_de_chofer,descuento",
            "monto" => "required|numeric|min:0",
            "medio_pago" => "required_if:tipo,pago_de_chofer|in:efectivo,transferencia,mercadopago",
            "comentario" => "nullable|string|max:191"
        ]);

        $alquiler = Alquiler::findOrFail($id);

        if($alquiler->puedeRegistrarMovimientos()) 
        {
            $fecha = Carbon::createFromFormat("d/m/Y", $request->fecha);

            $alquiler->agregarMovimientoRetroactivo(
                $fecha->isToday() ? Carbon::now() : $fecha,
                $request->tipo,
                $request->monto,
                $request->medio_pago,
                $request->comentario
            );
        }
        
        return redirect()->route("alquileres.show", $alquiler->id);
    }



}

resources/views/alquileres/create.blade.php
@extends('layouts.main')

@section('title', 'Registrar alquiler')


@section('custom-css')
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css') }}">
@endsection


@section('content')

					<h3 class="page-title"><a href="{{ route('alquileres.index') }}">Alquileres</a> / Registrar nuevo alquiler</h3>

					<div class="row">
						<div class="col-md-6">

							<div class="panel panel-headline">
								<div class="panel-heading">
									<h3 class="panel-title">Detalles del alquiler</h3>
								</div>

								<div class="panel-body">

									<form method="POST" action="{{ route('alquileres.store') }}">
										@csrf
										<div class="row">
											<div class="col-sm-6">
												<div class="form-group">
													<label>Fecha de inicio</label>
													<input type="text" class="form-control" value="{{ Carbon\Carbon::today()->format('d/m/Y') }}" readonly="">
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group @error('fecha_fin') has-error @enderror">
													
													<label>Fecha de fin</label>
													
													<label class="fancy-checkbox">
														<input type="checkbox" name="alquiler_indefinido" id="checkbox_fin_alquiler_indefinido" @if(old('alquiler_indefinido')) checked @endif>
														<span>Sin fecha definida (el alquiler se termina manualmente)</span>
													</label>
													
													<input type="text" name="fecha_fin" class="form-control" id="input_fecha_fin_alquiler" value="{{ old('fecha_fin') }}">
													
													@error('fecha_fin')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-sm-6">
												<div class="form-group @error('id_chofer') has-error @enderror">
													<label>Chofer</label>
													
													<select class="form-control" name="id_chofer">
														<option value="">Seleccionar</option>
														
														@foreach($choferesDisponibles as $chofer)
															<option value="{{ $chofer->id }}" @if(old('id_chofer') == $chofer->id) selected @endif>{{ $chofer->nombre_y_apellido }}</option>
														@endforeach

													</select>

													@error('id_chofer')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group @error('id_vehiculo') has-error @enderror">
													<label>Vehículo</label>
													
													<select class="form-control" name="id_vehiculo">
														<option value="">Seleccionar</option>

														@foreach($vehiculosDisponibles as $vehiculo)
															<option value="{{ $vehiculo->id }}" @if(old('id_vehiculo') == $vehiculo->id) selected @endif>{{ $vehiculo->marcaModeloYDominio() }}</option>
														@endforeach

													</select>

													@error('id_vehiculo')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
										</div>





										<div class="row">
											<div class="col-sm-6">
												<div class="form-group @error('precio_diario') has-error @enderror">
													<label>Monto diario de alquiler ($)&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-question-sign" style="color:#45bac6" data-toggle="tooltip" data-placement="top" title="El alquiler tendrá una cuenta corriente desde donde se descontará este monto diariamente, y paralelamente, se deberán registrar los pagos del chofer manualmente."></span></label>
													
													<input type="number" name="precio_diario" step="0.01" min="0" class="form-control" value="{{ old('precio_diario') }}">
													
													@error('precio_diario')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<label>Descuento semanal</label>
													<label class="fancy-checkbox">
														<input type="checkbox" name="descuento_semanal" @if(old('descuento_semanal')) checked @endif>
														<span>No cobrar el alquiler de los días domingo</span>
													</label>
												</div>
											</div>
										</div>
										<div class="form-group @error('notas') has-error @enderror">
											<label>Notas</label>
											<textarea class="form-control" name="notas" style="resize: vertical;">{{ old('notas') }}</textarea>
											@error('notas')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>

										<div style="text-align:right">
											<button class="btn btn-primary">Registrar alquiler</button>
										</div>
									</form>
									

								</div>
							</div>

						</div>

						<div class="col-md-6">
						</div>
					</div>



@endsection



@section('custom-js')
	<script src="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.es.min.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() 
		{

			// Config

			$('#input_fecha_fin_alquiler').datepicker({
				autoclose: true,
				language: 'es-ES',
				format: 'dd/mm/yyyy',
				orientation: 'bottom',
				startDate: '+1d',
				endDate: '+1y'
			});


			$("#checkbox_fin_alquiler_indefinido").change(function() {
				$("#input_fecha_fin_alquiler").prop("disabled", $(this).prop("checked"));
			})


			// Actions
			$("#checkbox_fin_alquiler_indefinido").trigger("change");

		});


	</script>	
@endsection

resources/views/alquileres/index.blade.php
@extends('layouts.main')

@section('title', 'Alquileres')



@section('content')
					<h3 class="page-title">Alquileres</h3>

					<div class="panel panel-headline">
						<div class="panel-heading">
							<h3 class="panel-title">Listado de alquileres</h3>

							<div class="right">
								<a href="{{ route('alquileres.create') }}" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;&nbsp;Registrar nuevo alquiler</a>
							</div>
						</div>

						<div class="panel-body">

							<div class="clearfix" style="margin-bottom: 10px">
								<div style="float: right;">
									Ordenar por
									<select class="form-control filter-select" name="orden" autocomplete="off">
										<option value="fecha_inicio_desc" {{ request()->orden == "fecha_inicio_desc" ? "selected" : "" }}>Iniciado recientemente</option>
										<option value="nombre_chofer_asc" {{ request()->orden == "nombre_chofer_asc" ? "selected" : "" }}>Nombre de chofer (A-Z)</option>
										<option value="nombre_vehiculo_asc" {{ request()->orden == "nombre_vehiculo_asc" ? "selected" : "" }}>Nombre de vehiculo (A-Z)</option>
										<option value="monto_diario_asc" {{ request()->orden == "monto_diario_asc" ? "selected" : "" }}>Monto diario (menor a mayor)</option>
										<option value="monto_diario_desc" {{ request()->orden == "monto_diario_desc" ? "selected" : "" }}>Monto diario (mayor a menor)</option>
										<option value="saldo_asc" {{ request()->orden == "saldo_asc" ? "selected" : "" }}>Saldo (menor a mayor)</option>
										<option value="saldo_desc" {{ request()->orden == "saldo_desc" ? "selected" : "" }}>Saldo (mayor a menor)</option>
									</select>
								</div>

								<div style="float: right; margin-right: 40px">
									Filtrar por estado
									<select class="form-control filter-select" name="estado" autocomplete="off">
										<option value="todos" {{ request()->estado == "todos" ? "selected" : "" }}>Todos</option>
										<option value="en_curso" {{ request()->estado == "en_curso" ? "selected" : "" }}>Activo</option>
										<option value="finalizado" {{ request()->estado == "finalizado" ? "selected" : "" }}>Finalizado</option>
									</select>
								</div>

								<div style="float: right; margin-right: 40px">
									Filtrar por vehículo
									<select class="form-control filter-select" name="vehiculo" autocomplete="off">
										<option value="todos">Todos</option>
										@foreach($vehiculos as $vehiculo)
										<option value="{{ $vehiculo->id }}" {{ request()->vehiculo == $vehiculo->id ? "selected" : "" }}>{{ $vehiculo->modeloYDominio() }}</option>
										@endforeach
									</select>
								</div>

							</div>

							<table class="table table-striped">
								<thead>
									<tr>
										<th></th>
										<th>ID #</th>
										<th>Estado</th>
										<th>Vehículo</th>
										<th>Fecha inicio</th>
										<th>Fecha fin</th>
										<th>Chofer</th>
										<th>Monto diario</th>
										<th>Saldo</th>
										<th>Notas</th>
									</tr>
								</thead>
								<tbody>
									
									@foreach($alquileres as $alquiler)
									<tr>
										<td><a href="{{ route('alquileres.show', $alquiler->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-search-plus" aria-hidden="true"></i></a></td>
										<td>{{ $alquiler->id }}</td>
										<td>
											@if($alquiler->estaEnCurso())
											<span class="label label-primary" style="font-size: 14px">En curso</span>
											@elseif($alquiler->estaFinalizado())
											<span class="label label-default" style="font-size: 14px">Finalizado</span>
											@endif
										</td>
										<td>{{ $alquiler->vehiculo->marcaModeloYDominio() }}</td>
										<td>{{ $alquiler->fecha_inicio->isoFormat('D MMM Y') }}</td>
										<td>{{ $alquiler->fecha_fin ? $alquiler->fecha_fin->isoFormat('D MMM Y') : '-' }}</td>
										<td>{{ $alquiler->chofer->nombre_y_apellido }}</td>
										<td>{{ Strings::formatearMoneda($alquiler->precio_diario, 0) }}</td>
										<td><span style="@if($alquiler->saldo_actual < 0) color: #B00 @endif">
											{{ Strings::formatearMoneda($alquiler->saldo_actual, 0) }}
										</span></td>
										<td>
											@if($alquiler->notas)
											<span class="glyphicon glyphicon-comment" style="font-size: 18px" data-toggle="tooltip" data-placement="top" title="{{ $alquiler->notas }}"></span>
											@endif
										</td>
									</tr>
									@endforeach

									@if($alquileres->count() == 0)
									<tr><td colspan="10" style="text-align: center;">No se encontraron alquileres.</td></tr>
									@endif

								</tbody>
							</table>

							<div style="text-align: center;">
								{{ $alquileres->appends(request()->input())->links() }}
							</div>

						</div>
					</div>

@endsection

resources/views/alquileres/show.blade.php
@extends('layouts.main')

@section('title', 'Detalles de alquiler')


@section('content')

					<h3 class="page-title"><a href="{{ route('alquileres.index') }}">Alquileres</a> / Alquiler #{{ $alquiler->id }}</h3>

						@if($alquiler->puedeRegistrarMovimientos() || $alquiler->estaEnCurso())
						<div class="panel panel-headline">
							<div class="panel-body">
								<div class="btn-group">
									
									@if($alquiler->puedeRegistrarMovimientos())
									<a href="{{ route('alquileres.registrar-pago', 1) }}" class="btn btn-primary"><span class="glyphicon glyphicon-usd"></span> Registrar pago o dto.</a>
									@endif

									@if($alquiler->estaEnCurso())
									<button class="btn btn-default" style="margin-left: 15px" onclick="if(confirm('¿Deseás terminar el alquiler? Una vez terminado no se podrá reanudar.')) $('#terminar-alq-form').submit();">Terminar alquiler</button>

									<form id="terminar-alq-form" action="{{ route('alquileres.terminar', $alquiler->id) }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                    @endif
                                    
								</div>
							</div>
						</div>
						@endif

					<div class="row">
						<div class="col-lg-6">
							<div class="panel panel-headline">
								<div class="panel-heading">
									<h3 class="panel-title">Detalles del alquiler</h3>
								</div>

								<div class="panel-body">

									<div class="row" style="margin-bottom: 30px">
										<div class="col-md-4">
											<label>Estado:</label>&nbsp;&nbsp;&nbsp;
											@if($alquiler->estaEnCurso())
											<span class="label label-primary" style="font-size: 14px;">En curso</span>
											@elseif($alquiler->estaFinalizado())
											<span class="label label-default" style="font-size: 14px;">Finalizado</span>
											@endif
										</div>
										<div class="col-md-4">
											<label>Fecha inicio:</label> {{ $alquiler->fecha_inicio->isoFormat('D MMM Y') }}
										</div>
										<div class="col-md-4">
											<label>Fecha fin:</label> 
											@if($alquiler->fecha_fin)
											{{ $alquiler->fecha_fin->isoFormat('D MMM Y') }}
											@else
											No definida
											@endif
										</div>
									</div>

									<div class="row" style="margin-bottom: 30px">
										<div class="col-md-6">
											<label>Chofer:</label> 
											@if(!$alquiler->chofer->trashed())
											<a href="{{ route('choferes.show', $alquiler->chofer->id) }}">{{ $alquiler->chofer->nombre_y_apellido }}</a>
											@else
											{{ $alquiler->chofer->nombre_y_apellido }}
											@endif
										</div>
										<div class="col-md-6">
											<label>Vehículo:</label>
											@if(!$alquiler->vehiculo->trashed())
											<a href="{{ route('vehiculos.show', $alquiler->vehiculo->id) }}">{{ $alquiler->vehiculo->marcaModeloYDominio() }}</a>
											@else
											{{ $alquiler->vehiculo->marcaModeloYDominio() }}
											@endif
										</div>
									</div>

									<div class="row" style="margin-bottom: 30px">
										<div class="col-md-6">
											<label>Precio diario:</label> {{ Strings::formatearMoneda($alquiler->precio_diario, 2) }}
										</div>
										<div class="col-md-6">
											<label>Descuento semanal:</label> @if($alquiler->descuento_semanal) Sí @else No @endif
											&nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-question-sign" style="color:#45bac6" data-toggle="tooltip" data-placement="top" title="Si se omite el cobro diario en los días domingo."></span>
										</div>
									</div>

									<div class="row" style="margin-bottom: 30px">
										<div class="col-md-6">
											<label>Pagos de chofer totales:</label> {{ Strings::formatearMoneda($alquiler->calcularIngresosTotales(), 2) }}
										</div>
									</div>

									<form method="POST" action="{{ route('alquileres.update', $alquiler->id) }}">
										@csrf
										@method('PUT')
										<div class="form-group @error('notas') has-error @enderror">
											<label>Notas</label>
											<textarea class="form-control" style="resize: vertical;" name="notas">{{ $alquiler->notas }}</textarea>
											@error('notas')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>

										<div style="text-align:right">
											<button class="btn btn-primary">Guardar</button>
										</div>
									</form>

								</div>
							</div>
						</div>

						<div class="col-lg-6">
							<div class="panel panel-headline">
								<div class="panel-heading">
									<h3 class="panel-title">Cuenta corriente</h3>
									<div class="right">
										<div style="font-size: 19px">
											<label>Saldo</label> 
											<span @if($alquiler->saldo_actual < 0) style="color: #B00;" @endif>
												{{ Strings::formatearMoneda($alquiler->saldo_actual, 2) }}
											</span>
										</div>
									</div>
								</div>

								<div class="panel-body">			

									<h4>Movimientos</h4>

									<table class="table">
										<thead>
											<tr>
												<th>Fecha</th>
												<th>Concepto</th>
												<th>Monto</th>
												<th>Saldo</th>
												<th>Medio de pago</th>
												<th>Coment.</th>
											</tr>
										</thead>
										<tbody>
											@foreach($movimientosSaldo as $movimiento)
											<tr>
												<td>{{ $movimiento->fecha_hora->isoFormat('D MMM Y') }}</td>
												<td>
													@if($movimiento->esCobroDeAlquiler())
													Cobro de alquiler
													@elseif($movimiento->esPagoDeChofer())
													Pago de chofer
													@elseif($movimiento->esDescuento())
													Descuento
													@endif
												</td>
												<td><span @if($movimiento->monto < 0) style="color: #B00;" @endif>
													{{ Strings::formatearMoneda($movimiento->monto, 2) }}
												</span></td>
												<td><span @if($movimiento->nuevo_saldo < 0) style="color: #B00;" @endif>
													{{ Strings::formatearMoneda($movimiento->nuevo_saldo, 2) }}
												</span></td>
												<td>
													@if($movimiento->esPagoDeChofer())
														@if($movimiento->esPorMercadopago())
														Mercadopago
														@elseif($movimiento->esEnEfectivo())
														Efectivo
														@elseif($movimiento->esPorTransferencia())
														Transferencia/depósito
														@endif
													@endif
												</td>
												<td>
													@if($movimiento->comentario)
													<span class="glyphicon glyphicon-comment" style="font-size: 18px" data-toggle="tooltip" data-placement="top" title="{{ $movimiento->comentario }}"></span>
													@endif
												</td>
											</tr>
											@endforeach

											@if($movimientosSaldo->count() == 0)
											<tr><td colspan="6" style="text-align: center;">No se encontraron movimientos.</td></tr>
											@endif
										</tbody>
									</table>	

								</div>
							</div>
						</div>
					</div>


@endsection