routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('mailable', function () {
    $tareaPendiente = App\TareaPendiente::find(13);

    return new App\Mail\NotificacionTareaPendiente($tareaPendiente);
});

// Auth
Route::get("login", "Auth\LoginController@showLoginForm")->name("login");
Route::post("login", "Auth\LoginController@login");
Route::post("logout", "Auth\LoginController@logout")->name("logout");

// Cuenta
Route::get("cuenta", "UsuarioController@detalles")->name("cuenta.detalles");
Route::post("cuenta", "UsuarioController@modificar");
Route::get("cuenta/cambiar-password", "UsuarioController@formularioPassword")->name("cuenta.cambiar-password");
Route::post("cuenta/cambiar-password", "UsuarioController@cambiarPassword");

// Inicio
Route::get("/", "InicioController@index")->name("inicio");

// Choferes
Route::resource("choferes", "ChoferesController")->except(["edit"]);

// Proveedores
Route::resource("proveedores", "ProveedoresController")->except(["edit"]);

// Vehiculos
Route::resource("vehiculos", "VehiculosController")->except(["edit"]);
Route::get("vehiculos/{id}/registrar-kilometraje", "VehiculosController@formularioRegistrarKms")->name("vehiculos.registrar-kilometraje");
Route::post("vehiculos/{id}/registrar-kilometraje", "VehiculosController@registrarKms");

// Trabajos de vehiculos
Route::resource("trabajos-vehiculos", "TrabajosVehiculosController")->except(["edit", "destroy"]);

// Alquileres
Route::get("alquileres/registrar", "AlquileresController@create")->name("alquileres.create");
Route::resource("alquileres", "AlquileresController")->except(["create", "edit", "destroy"]);

Route::post("alquileres/{id}/terminar", "AlquileresController@terminar")->name("alquileres.terminar");
Route::get("alquileres/{id}/registrar-pago", "AlquileresController@formularioRegistrarPago")->name("alquileres.registrar-pago");
Route::post("alquileres/{id}/registrar-pago", "AlquileresController@registrarPago");

// Gastos adicionales
Route::resource("gastos-adicionales", "GastosAdicionalesController")->except(["edit", "destroy"]);

// Reportes
Route::get("reportes/balances", "ReportesController@mostrarBalances")->name("reportes.balances");
Route::get("reportes/vehiculos", "ReportesController@mostrarVehiculos")->name("reportes.vehiculos");
Route::get("reportes/choferes", "ReportesController@mostrarChoferes")->name("reportes.choferes");

app/Http/Controllers/GastosAdicionalesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CrearGastoAdicional;
use Illuminate\Http\Request;
use App\GastoAdicional;
use App\Vehiculo;
use App\Proveedor;
use App\Http\Filters\FiltrosGastosAdicionales;

class GastosAdicionalesController extends AdminPanelBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(FiltrosGastosAdicionales $filtros)
    {
        $gastosAdicionales = GastoAdicional::with(["vehiculo", "proveedor"])->filter($filtros)->paginate(15);

        return view("gastos-adicionales.index")->with([
            "gastosAdicionales" => $gastosAdicionales,
            "vehiculosConDebito" => Vehiculo::conAlgunDebitoAutomatico()->get()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("gastos-adicionales.create")->with([
            "vehiculos" => Vehiculo::nombreAsc()->get(),
            "proveedores" => Proveedor::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CrearGastoAdicional $request)
    {
        GastoAdicional::create($request->all());

        return redirect()->route("gastos-adicionales.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $gastoAdicional = GastoAdicional::with(["vehiculo", "proveedor"])->findOrFail($id);

        return view("gastos-adicionales.show")->with("gasto", $gastoAdicional);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(["detalle" => "nullable|max:100"]);

        $gastoAdicional = GastoAdicional::findOrFail($id);
        $gastoAdicional->detalle = $request->detalle;
        $gastoAdicional->save();

        return redirect()->back()->with("success", true);
    }
}

resources/views/gastos-adicionales/create.blade.php
@extends('layouts.main')

@section('title', 'Agregar gasto')


@section('custom-css')
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css') }}">
@endsection


@section('content')

					<h3 class="page-title"><a href="{{ route('gastos-adicionales.index') }}">Gastos adicionales</a> / Registrar</h3>

					<div class="row">
						<div class="col-md-6">

							<div class="panel panel-headline">
								<div class="panel-heading">
									<h3 class="panel-title">Detalles del gasto</h3>
								</div>

								<div class="panel-body">

									<form method="POST" action="{{ route('gastos-adicionales.store') }}">
										@csrf

										<div class="row">
											<div class="col-xs-6">
												<div class="form-group @error('fecha') has-error @enderror">
													<label>Fecha</label>
													<input type="text" class="form-control" id="input_fecha_gasto" name="fecha" value="{{ old('fecha') }}">
													@error('fecha')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-xs-6">
												<div class="form-group @error('tipo') has-error @enderror">
													<label>Tipo de gasto</label>
													<select class="form-control" name="tipo">
														<option value="">Seleccionar</option>
														<option value="seguro_vehiculo" @if(old('tipo') == 'seguro_vehiculo') selected @endif>Pago de seguro</option>
														<option value="impuesto_automotor" @if(old('tipo') == 'impuesto_automotor') selected @endif>Impuesto automotor</option>
														<option value="otro" @if(old('tipo') == 'otro') selected @endif>Otro</option>
													</select>
													@error('tipo')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
											<div class="col-xs-6">
												<div class="form-group @error('detalle') has-error @enderror">
													<label>Detalle (opcional)</label>
													<input type="text" class="form-control" name="detalle" value="{{ old('detalle') }}">
													@error('detalle')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
										</div>

										<div class="form-group @error('id_vehiculo') has-error @enderror">
											<label>Vehículo asociado al gasto</label>
											<select class="form-control" name="id_vehiculo">
												<option value="">Ninguno</option>
												@foreach($vehiculos as $vehiculo)
												<option value="{{ $vehiculo->id }}" @if(old('id_vehiculo') == $vehiculo->id) selected @endif>{{ $vehiculo->marcaModeloYDominio() }}</option>
												@endforeach
											</select>
											@error('id_vehiculo')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>

										<div class="row">
											<div class="col-xs-6">
												<div class="form-group @error('monto') has-error @enderror">
													<label>Monto ($)</label>
													<input type="number" step="0.01" min="0" class="form-control" name="monto" value="{{ old('monto') }}">
													@error('monto')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
											<div class="col-xs-6">
												<div class="form-group @error('medio_pago') has-error @enderror">
													<label>Medio de pago</label>
													<select class="form-control" name="medio_pago">
														<option value="">Seleccionar</option>
														<option value="efectivo" @if(old('medio_pago') == 'efectivo') selected @endif>Efectivo</option>
														<option value="tarjeta_credito" @if(old('medio_pago') == 'tarjeta_credito') selected @endif>Tarjeta de crédito</option>
														<option value="transferencia" @if(old('medio_pago') == 'transferencia') selected @endif>Transferencia bancaria</option>
													</select>
													@error('medio_pago')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
										</div>

										<div class="form-group @error('id_proveedor') has-error @enderror">
											<label>Proveedor asociado al gasto</label>
											<select class="form-control" name="id_proveedor">
												<option value="">Ninguno</option>
												@foreach($proveedores as $proveedor)
												<option value="{{ $proveedor->id }}" @if(old('id_proveedor') == $proveedor->id) selected @endif>{{ $proveedor->nombre }}</option>
												@endforeach
											</select>
											@error('id_proveedor')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>

										<div style="text-align:right">
											<button class="btn btn-primary">Guardar</button>
										</div>
									</form>
									

								</div>
							</div>

						</div>

						<div class="col-md-6">
						</div>
					</div>



@endsection



@section('custom-js')
	<script src="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.es.min.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() 
		{

			$('#input_fecha_gasto').datepicker({
				autoclose: true,
				language: 'es-ES',
				format: 'dd/mm/yyyy',
				orientation: 'bottom',
				startDate: '-30d',
				endDate: 'today'
			});


			$("#checkbox_fin_alquiler_indefinido").change(function() {
				$("#input_fecha_fin_alquiler").prop("disabled", $(this).prop("checked"));
			})

		});


	</script>
@endsection

resources/views/gastos-adicionales/index.blade.php
@extends('layouts.main')

@section('title', 'Gastos adicionales')



@section('content')
					<h3 class="page-title">Gastos adicionales</h3>

					<div class="panel panel-headline">
						<div class="panel-heading">
							<h3 class="panel-title">Registro de gastos adicionales &nbsp;&nbsp;&nbsp;<span class="glyphicon glyphicon-question-sign" style="color:#45bac6;font-size: 17px" data-toggle="tooltip" data-placement="right" title="Registro de cualquier gasto no encuadrado en trabajos sobre vehículos: pago de seguros, patentes, compra de insumos, etc. Estos servirán para generar reportes completos de balances del negocio."></span></h3>

							<div class="right">
								<a href="{{ route('gastos-adicionales.create') }}" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;&nbsp;Registrar nuevo gasto</a>
							</div>
						</div>

						<div class="panel-body">

							<div class="clearfix" style="margin-bottom: 10px">
								<div style="float: right;">
									Ordenar por
									<select class="form-control filter-select" name="orden" autocomplete="off">
										<option value="fecha_desc" {{ request()->orden == "fecha_desc" ? "selected" : "" }}>Realizado recientemente</option>
										<option value="nombre_veh_asc" {{ request()->orden == "nombre_veh_asc" ? "selected" : "" }}>Nombre de vehiculo (A-Z)</option>
										<option value="monto_asc" {{ request()->orden == "monto_asc" ? "selected" : "" }}>Monto (menor a mayor)</option>
										<option value="monto_desc" {{ request()->orden == "monto_desc" ? "selected" : "" }}>Monto (mayor a menor)</option>
										<option value="nombre_prov_asc" {{ request()->orden == "nombre_prov_asc" ? "selected" : "" }}>Nombre de proveedor (A-Z)</option>
										<option value="nombre_prov_desc" {{ request()->orden == "nombre_prov_desc" ? "selected" : "" }}>Nombre de proveedor (Z-A)</option>
									</select>
								</div>

								<div style="float: right; margin-right: 40px">
									Filtrar medio de pago
									<select class="form-control filter-select" name="medio_pago" autocomplete="off">
										<option value="todos" {{ request()->medio_pago == "todos" ? "selected" : "" }}>Todos</option>
										<option value="efectivo" {{ request()->medio_pago == "efectivo" ? "selected" : "" }}>Efectivo</option>
										<option value="tarjeta_credito" {{ request()->medio_pago == "tarjeta_credito" ? "selected" : "" }}>Tarjeta de crédito</option>
										<option value="transferencia" {{ request()->medio_pago == "transferencia" ? "selected" : "" }}>Transf./depósito</option>
									</select>
								</div>

								<div style="float: right; margin-right: 40px">
									Filtrar por tipo de gasto
									<select class="form-control filter-select" name="tipo_gasto" autocomplete="off">
										<option value="todos" {{ request()->tipo_gasto == "todos" ? "selected" : "" }}>Todos</option>
										<option value="seguro_vehiculo" {{ request()->tipo_gasto == "seguro_vehiculo" ? "selected" : "" }}>Seguro de vehículo</option>
										<option value="impuesto_automotor" {{ request()->tipo_gasto == "impuesto_automotor" ? "selected" : "" }}>Impuesto automotor</option>
										<option value="otro" {{ request()->tipo_gasto == "otro" ? "selected" : "" }}>Otro</option>
									</select>
								</div>
							</div>

							<table class="table table-striped">
								<thead>
									<tr>
										<th></th>
										<th>ID #</th>
										<th>Fecha</th>
										<th>Tipo de gasto</th>
										<th>Detalle</th>
										<th>Vehículo</th>
										<th>Monto</th>
										<th>Medio de pago</th>
										<th>Proveedor</th>
									</tr>
								</thead>
								<tbody>
									@foreach($gastosAdicionales as $gastoAdicional)
									<tr>
										<td><a href="{{ route('gastos-adicionales.show', $gastoAdicional->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-search-plus" aria-hidden="true"></i></a></td>
										<td>{{ $gastoAdicional->id }}</td>
										<td>{{ $gastoAdicional->fecha->isoFormat('D MMM Y') }}</td>
										<td>
											@if($gastoAdicional->tipo == 'seguro_vehiculo')
											Seguro de vehículo
											@elseif($gastoAdicional->tipo == 'impuesto_automotor')
											Impuesto automotor
											@elseif($gastoAdicional->tipo == 'otro')
											Otro
											@endif
										</td>
										<td>{{ Str::limit($gastoAdicional->detalle, 40, '...') }}</td>
										<td>{{ $gastoAdicional->vehiculo ? $gastoAdicional->vehiculo->marcaModeloYDominio() : '-' }}</td>
										<td>{{ Strings::formatearMoneda($gastoAdicional->monto, 2) }}</td>
										<td>{{ __('medios_pago.'.$gastoAdicional->medio_pago) }}</td>
										<td>{{ $gastoAdicional->proveedor ? $gastoAdicional->proveedor->nombre : '-' }}</td>
									</tr>
									@endforeach

									@if($gastosAdicionales->count() == 0)
									<tr><td colspan="9" style="text-align: center;">No se registraron gastos adicionales.</td></tr>
									@endif

								</tbody>
							</table>

							<div style="text-align: center;">
								{{ $gastosAdicionales->appends(request()->input())->links() }}
							</div>

						</div>
					</div>

					<div class="row">
						<div class="col-md-6">

							<div class="panel">
								<div class="panel-heading">
									<h3 class="panel-title">Gastos con débito automático</h3>
									<div class="right">
										<button type="button" class="btn-toggle-collapse compact"><i class="lnr lnr-chevron-up"></i></button>
									</div>
								</div>
								<div class="panel-body">

									<h5>Gastos que se registran automáticamente todos los meses (con tarjeta de crédito)</h5>

									<table class="table">
										<thead>
											<tr>
												<th>Día del mes débito</th>
												<th>Vehiculo</th>
												<th>Tipo de gasto</th>
												<th>Monto</th>
											</tr>
										</thead>
										<tbody>
											@foreach($vehiculosConDebito as $vehiculo)

												@if($vehiculo->tieneDebitoAutomPatentes())
												<tr>
													<td>{{ $vehiculo->dia_del_mes_debito_imp_automotor }}</td>
													<td>{{ $vehiculo->marcaModeloYDominio() }}</td>
													<td>Impuesto automotor</td>
													<td>{{ Strings::formatearMoneda($vehiculo->costo_mensual_imp_automotor, 2) }}</td>
												</tr>
												@endif

												@if($vehiculo->tieneDebitoAutomSeguro())
												<tr>
													<td>{{ $vehiculo->dia_del_mes_debito_seguro }}</td>
													<td>{{ $vehiculo->marcaModeloYDominio() }}</td>
													<td>Seguro</td>
													<td>{{ Strings::formatearMoneda($vehiculo->costo_mensual_seguro, 2) }}</td>
												</tr>
												@endif

											@endforeach

										</tbody>
									</table>

									
								</div>
							</div>

						</div>
					</div>



@endsection

resources/views/gastos-adicionales/show.blade.php
@extends('layouts.main')

@section('title', 'Detalles de gasto')



@section('content')

					<h3 class="page-title"><a href="{{ route('gastos-adicionales.index') }}">Gastos adicionales</a> / Gasto #{{ $gasto->id }}</h3>

					<div class="panel panel-headline">
						<div class="panel-body">
							<div class="btn-group">
								<button class="btn btn-danger"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar gasto</button>
							</div>
						</div>
					</div>

					@if(session('success'))
					<div class="alert alert-success alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						Los datos se actualizaron correctamente.
					</div>
					@endif

					<div class="row">
						<div class="col-md-6">

							<div class="panel panel-headline">
								<div class="panel-heading">
									<h3 class="panel-title">Detalles del gasto</h3>
								</div>

								<div class="panel-body">

									<form action="{{ route('gastos-adicionales.update', $gasto->id) }}" method="POST">
										@method('PUT')
										@csrf

										<div class="row">
											<div class="col-xs-6">
												<div class="form-group">
													<label>Fecha</label><br/>
													{{ $gasto->fecha->isoFormat('D MMM Y') }}
												</div>
											</div>
										</div>

										<div class="row">
											<div class="col-xs-6">
												<div class="form-group">
													<label>Tipo de gasto</label><br/>
													@if($gasto->tipo == 'seguro_vehiculo')
													Pago de seguro
													@elseif($gasto->tipo == 'impuesto_automotor')
													Impuesto automotor
													@elseif($gasto->tipo == 'otro')
													Otro
													@endif
													Otro
												</div>
											</div>
											<div class="col-xs-6">
												<div class="form-group @error('detalle') has-error @enderror">
													<label>Detalle</label>
													<input type="text" class="form-control" name="detalle" value="{{ $gasto->detalle }}">
													@error('detalle')
														<label class="control-label">{{ $message }}</label>
													@enderror
												</div>
											</div>
										</div>

										<div class="form-group">
											<label>Vehículo asociado al gasto</label><br/>
											@if($gasto->vehiculo)
												@if(!$gasto->vehiculo->trashed())
												<a href="{{ route('vehiculos.show', $gasto->vehiculo->id) }}">{{ $gasto->vehiculo->marcaModeloYDominio() }}</a>
												@else
												{{ $gasto->vehiculo->marcaModeloYDominio() }}
												@endif
											@else
											-
											@endif
										</div>

										<div class="row">
											<div class="col-xs-6">
												<div class="form-group">
													<label>Monto ($)</label><br/>
													{{ Strings::formatearMoneda($gasto->monto,2) }}
												</div>
											</div>
											<div class="col-xs-6">
												<div class="form-group">
													<label>Medio de pago</label><br/>
													@if($gasto->medio_pago == 'efectivo')
													Efectivo
													@elseif($gasto->medio_pago == 'tarjeta_credito')
													Tarjeta de crédito
													@elseif($gasto->medio_pago == 'transferencia')
													Transferencia bancaria
													@endif
												</div>
											</div>
										</div>

										<div class="form-group">
											<label>Proveedor asociado al gasto</label><br/>
											@if($gasto->proveedor)
												@if(!$gasto->proveedor->trashed())
												<a href="{{ route('proveedores.show', $gasto->proveedor->id) }}">{{ $gasto->proveedor->nombre }}</a>
												@else
												{{ $gasto->proveedor->nombre }}
												@endif
											@else
											-
											@endif
										</div>

										<div style="text-align:right">
											<button class="btn btn-primary">Guardar</button>
										</div>
									</form>
									

								</div>
							</div>

						</div>

						<div class="col-md-6">
						</div>
					</div>


@endsection