routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('mailable', function () {
    $tareaPendiente = App\TareaPendiente::find(13);

    return new App\Mail\NotificacionTareaPendiente($tareaPendiente);
});

// Auth
Route::get("login", "Auth\LoginController@showLoginForm")->name("login");
Route::post("login", "Auth\LoginController@login");
Route::post("logout", "Auth\LoginController@logout")->name("logout");

// Cuenta
Route::get("cuenta", "UsuarioController@detalles")->name("cuenta.detalles");
Route::post("cuenta", "UsuarioController@modificar");
Route::get("cuenta/cambiar-password", "UsuarioController@formularioPassword")->name("cuenta.cambiar-password");
Route::post("cuenta/cambiar-password", "UsuarioController@cambiarPassword");

// Inicio
Route::get("/", "InicioController@index")->name("inicio");

// Choferes
Route::resource("choferes", "ChoferesController")->except(["edit"]);

// Proveedores
Route::resource("proveedores", "ProveedoresController")->except(["edit"]);

// Vehiculos
Route::resource("vehiculos", "VehiculosController")->except(["edit"]);
Route::get("vehiculos/{id}/registrar-kilometraje", "VehiculosController@formularioRegistrarKms")->name("vehiculos.registrar-kilometraje");
Route::post("vehiculos/{id}/registrar-kilometraje", "VehiculosController@registrarKms");

// Trabajos de vehiculos
Route::resource("trabajos-vehiculos", "TrabajosVehiculosController")->except(["edit", "destroy"]);

// Alquileres
Route::get("alquileres/registrar", "AlquileresController@create")->name("alquileres.create");
Route::resource("alquileres", "AlquileresController")->except(["create", "edit", "destroy"]);

Route::post("alquileres/{id}/terminar", "AlquileresController@terminar")->name("alquileres.terminar");
Route::get("alquileres/{id}/registrar-pago", "AlquileresController@formularioRegistrarPago")->name("alquileres.registrar-pago");
Route::post("alquileres/{id}/registrar-pago", "AlquileresController@registrarPago");

// Gastos adicionales
Route::resource("gastos-adicionales", "GastosAdicionalesController")->except(["edit", "destroy"]);

// Reportes
Route::get("reportes/balances", "ReportesController@mostrarBalances")->name("reportes.balances");
Route::get("reportes/vehiculos", "ReportesController@mostrarVehiculos")->name("reportes.vehiculos");
Route::get("reportes/choferes", "ReportesController@mostrarChoferes")->name("reportes.choferes");

app/Http/Controllers/ChoferesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CrearChofer;
use App\Http\Filters\FiltrosChoferes;
use Carbon\Carbon;
use App\Chofer;

class ChoferesController extends AdminPanelBaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(FiltrosChoferes $filtros)
    {
        $choferes = Chofer::with("alquilerActual.vehiculo")->filter($filtros)->paginate(15);

        return view("choferes.index")->with(["choferes" => $choferes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("choferes.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CrearChofer $request)
    {
        $chofer = new Chofer();
        $chofer->fill($request->all());
        $chofer->save();

        $chofer->registrarNotifDeVtoLicencia();

        return redirect()->route('choferes.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $chofer = Chofer::findOrFail($id);
        $ultimosAlquileres = $chofer->alquileres()->with("vehiculo")->fechaDesc()->limit(8)->get();

        return view("choferes.show")->with([
            "chofer" => $chofer,
            "ultimosAlquileres" => $ultimosAlquileres
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CrearChofer $request, $id)
    {
        $chofer = Chofer::findOrFail($id);
        $chofer->fill($request->all());
        $chofer->save();

        $chofer->actualizarNotifVtoLicenciaSiCambio();

        return redirect()->back()->with("success", true);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $chofer = Chofer::findOrFail($id);

        if(!$chofer->estaAlquilando()) 
        {
            $chofer->tareasPendientes()->delete();
            $chofer->delete(); // soft delete
        }

        return redirect()->route('choferes.index');
    }
}

resources/views/choferes/create.blade.php
@extends('layouts.main')

@section('title', 'Agregar chofer')


@section('custom-css')
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css') }}">
@endsection


@section('content')

					<h3 class="page-title"><a href="{{ route('choferes.index') }}">Choferes</a> / Agregar</h3>

					<div class="row">
						<div class="col-md-6">

							<div class="panel panel-headline">
								<div class="panel-heading">
									<h3 class="panel-title">Detalles del chofer</h3>
								</div>

								<div class="panel-body">

									<form action="{{ route('choferes.store') }}" method="POST">
										@csrf
										<div class="form-group @error('nombre_y_apellido') has-error @enderror">
											<label>Nombre y apellido</label>
											<input type="text" name="nombre_y_apellido" class="form-control" value="{{ old('nombre_y_apellido') }}">
											@error('nombre_y_apellido')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('telefono') has-error @enderror">
											<label>Teléfono</label>
											<input type="text" name="telefono" class="form-control" value="{{ old('telefono') }}">
											@error('telefono')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('direccion') has-error @enderror">
											<label>Dirección</label>
											<input type="text" name="direccion" class="form-control" value="{{ old('direccion') }}">
											@error('direccion')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('dni') has-error @enderror">
											<label>DNI</label>
											<input type="number" name="dni" class="form-control" value="{{ old('dni') }}">
											@error('dni')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('fecha_vto_licencia') has-error @enderror">
											
											<label>Fecha de vto. de licencia <span class="glyphicon glyphicon-question-sign" style="color:#45bac6" data-toggle="tooltip" data-placement="top" title="Ingresá la fecha para que se te notifique por email y por el sitio 10 días antes del vencimiento, sino dejalo vacío."></span></label>

											<input type="text" name="fecha_vto_licencia" class="form-control" id="input_fecha_vto_licencia" value="{{ old('fecha_vto_licencia') }}">
											@error('fecha_vto_licencia')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('notas') has-error @enderror">
											<label>Notas</label>
											<textarea class="form-control" name="notas" style="resize: vertical;">{{ old('notas') }}</textarea>
											@error('notas')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>

										<div style="text-align:right">
											<button class="btn btn-primary">Agregar chofer</button>
										</div>
									</form>
									

								</div>
							</div>

						</div>

						<div class="col-md-6">
						</div>
					</div>



@endsection



@section('custom-js')
	<script src="../assets/vendor/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js"></script>
	<script src="../assets/vendor/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.es.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function() 
		{

			$('#input_fecha_vto_licencia').datepicker({
				autoclose: true,
				language: 'es-ES',
				format: 'dd/mm/yyyy',
				orientation: 'bottom',
				startDate: 'tomorrow'
			});


		});
	</script>
@endsection

resources/views/choferes/index.blade.php
@extends('layouts.main')

@section('title', 'Choferes')



@section('content')
					<h3 class="page-title">Choferes</h3>

					<div class="panel panel-headline">
						<div class="panel-heading">
							<h3 class="panel-title">Listado de choferes</h3>

							<div class="right">
								<a href="{{ route('choferes.create') }}" class="btn btn-success"><i class="fa fa-plus"></i>&nbsp;&nbsp;Agregar</a>
							</div>
						</div>

						<div class="panel-body">

							<div class="clearfix" style="margin-bottom: 10px">
								<div style="float: right;">
									Ordenar por
									<select class="form-control filter-select" name="orden" autocomplete="off">
										<option value="fecha_desc" {{ request()->orden == "fecha_desc" ? "selected" : "" }}>Creado recientemente</option>
										<option value="modif_desc" {{ request()->orden == "modif_desc" ? "selected" : "" }}>Modificado recientemente</option>
										<option value="nombre_asc" {{ request()->orden == "nombre_asc" ? "selected" : "" }}>Nombre y apellido (A-Z)</option>
										<option value="nombre_desc" {{ request()->orden == "nombre_desc" ? "selected" : "" }}>Nombre y apellido (Z-A)</option>
									</select>
								</div>
							</div>

							<table class="table table-striped">
								<thead>
									<tr>
										<th></th>
										<th>Nombre y apellido</th>
										<th>DNI</th>
										<th>Teléfono</th>
										<th>Dirección</th>
										<th>Estado</th>
										<th>Vehiculo alquilado</th>
										<th>Notas</th>
									</tr>
								</thead>
								<tbody>
									@foreach($choferes as $chofer)
									<tr>
										<td><a href="{{ route('choferes.show', $chofer->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-search-plus" aria-hidden="true"></i></a></td>
										<td>{{ $chofer->nombre_y_apellido }}</td>
										<td>{{ $chofer->dni }}</td>
										<td>{{ $chofer->telefono }}</td>
										<td>{{ $chofer->direccion }}</td>
										<td>
											@if($chofer->alquilerActual)
											<span class="label label-success" style="font-size: 13px">Alquilando</span>
											@else
											<span class="label label-default" style="font-size: 13px">Disponible</span>
											@endif
										</td>
										<td>
											@if($chofer->alquilerActual)
											{{ $chofer->alquilerActual->vehiculo->marcaYModelo() }}
											@else
											-
											@endif
										</td>
										<td>{{ Str::limit($chofer->notas, 60, '...') }}</td>
									</tr>
									@endforeach

									@if($choferes->count() == 0)
									<tr><td colspan="6" style="text-align: center;">No se encontraron choferes.</td></tr>
									@endif

								</tbody>
							</table>

							<div style="text-align: center;">
								{{ $choferes->appends(request()->input())->links() }}
							</div>
						</div>
					</div>
@endsection

resources/views/choferes/show.blade.php
@extends('layouts.main')

@section('title', 'Detalles de chofer')

@section('custom-css')
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/css/bootstrap-datepicker.min.css') }}">
@endsection

@section('content')

					<h3 class="page-title"><a href="{{ route('choferes.index') }}">Choferes</a> / {{ $chofer->nombre_y_apellido }}</h3>

					@if(!$chofer->estaAlquilando())
					<div class="panel panel-headline">
						<div class="panel-body">
							<div class="btn-group">
								<button class="btn btn-danger" onclick="if(confirm('¿Confirma eliminar chofer? No se puede deshacer.')) $('#delete-form').submit();"><i class="fa fa-trash-o" aria-hidden="true"></i> Eliminar chofer</button>
							</div>
							<form action="{{ route('choferes.destroy', $chofer->id) }}" method="POST" id="delete-form" style="display: none">
								@method('DELETE')
								@csrf
							</form>
						</div>
					</div>
					@endif

					@if(session('success'))
					<div class="alert alert-success alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						Los datos se actualizaron correctamente.
					</div>
					@endif

					<div class="row">
						<div class="col-lg-6">
							<div class="panel panel-headline">
								<div class="panel-heading">
									<h3 class="panel-title">Detalles del chofer</h3>
								</div>

								<div class="panel-body">

									<form action="{{ route('choferes.update', $chofer->id) }}" method="POST">
										@method('PUT')
										@csrf
										<div class="form-group @error('nombre_y_apellido') has-error @enderror">
											<label>Nombre y apellido</label>
											<input type="text" name="nombre_y_apellido" class="form-control" value="{{ $chofer->nombre_y_apellido }}">
											@error('nombre_y_apellido')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('telefono') has-error @enderror">
											<label>Teléfono</label>
											<input type="text" name="telefono" class="form-control" value="{{ $chofer->telefono }}">
											@error('telefono')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('direccion') has-error @enderror">
											<label>Dirección</label>
											<input type="text" name="direccion" class="form-control" value="{{ $chofer->direccion }}">
											@error('direccion')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('dni') has-error @enderror">
											<label>DNI</label>
											<input type="number" name="dni" class="form-control" value="{{ $chofer->dni }}">
											@error('dni')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('fecha_vto_licencia') has-error @enderror">
											<label>Fecha de vto. de licencia <span class="glyphicon glyphicon-question-sign" style="color:#45bac6" data-toggle="tooltip" data-placement="top" title="Ingresá la fecha para que se te notifique por email y por el sitio 10 días antes del vencimiento, sino dejalo vacío."></span></label>
											<input type="text" name="fecha_vto_licencia" class="form-control" id="input_fecha_vto_licencia" value="{{ $chofer->fecha_vto_licencia ? $chofer->fecha_vto_licencia->format('d/m/Y') : '' }}">
											@error('fecha_vto_licencia')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>
										<div class="form-group @error('notas') has-error @enderror">
											<label>Notas</label>
											<textarea class="form-control" name="notas" style="resize: vertical;">{{ $chofer->notas }}</textarea>
											@error('notas')
												<label class="control-label">{{ $message }}</label>
											@enderror
										</div>

										<div style="text-align:right">
											<button class="btn btn-primary">Guardar</button>
										</div>
									</form>
									

								</div>
							</div>
						</div>

						<div class="col-lg-6">
							<div class="panel">
								<div class="panel-heading">
									<h3 class="panel-title">Alquileres recientes con este chofer</h3>
								</div>

								<div class="panel-body">

									<table class="table table-striped">
										<thead>
											<tr>
												<th></th>
												<th>ID #</th>
												<th>Estado</th>
												<th>Fecha inicio</th>
												<th>Fecha fin</th>
												<th>Vehículo</th>
												<th>Monto diario</th>
												<th>Saldo</th>
											</tr>
										</thead>
										<tbody>
											@foreach($ultimosAlquileres as $alquiler)
											<tr>
												<td><a href="{{ route('alquileres.show', $alquiler->id) }}" class="btn btn-primary btn-xs"><i class="fa fa-search-plus" aria-hidden="true"></i></a></td>
												<td>{{ $alquiler->id }}</td>
												<td>
												@if($alquiler->estaEnCurso())
												<span class="label label-primary" style="font-size: 12px">En curso</span>
												@elseif($alquiler->estaFinalizado())
												<span class="label label-default" style="font-size: 12px">Finalizado</span>
												@endif
												</td>
												<td>{{ $alquiler->fecha_inicio->isoFormat('D MMM') }}</td>
												<td>{{ $alquiler->fecha_fin ? $alquiler->fecha_fin->isoFormat('D MMM') : '-' }}</td>
												<td>{{ $alquiler->vehiculo->marcaYModelo() }}</td>
												<td>{{ Strings::formatearMoneda($alquiler->precio_diario, 0) }}</td>
												<td><span style="@if($alquiler->saldo_actual < 0) color: #B00 @endif">
												{{ Strings::formatearMoneda($alquiler->saldo_actual, 0) }}
												</span></td>
											</tr>
											@endforeach

											@if($ultimosAlquileres->count() == 0)
											<tr><td colspan="8" style="text-align: center;">No se encontraron alquileres.</td></tr>
											@endif

										</tbody>
									</table>

								</div>
							</div>
						</div>
					</div>


@endsection



@section('custom-js')
	<script src="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/js/bootstrap-datepicker.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-datepicker-1.9.0/locales/bootstrap-datepicker.es.min.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function() 
		{

			$('#input_fecha_vto_licencia').datepicker({
				autoclose: true,
				language: 'es-ES',
				format: 'dd/mm/yyyy',
				orientation: 'bottom',
				startDate: 'tomorrow'
			});


		});
	</script>
@endsection