routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('mailable', function () {
    $tareaPendiente = App\TareaPendiente::find(13);

    return new App\Mail\NotificacionTareaPendiente($tareaPendiente);
});

// Auth
Route::get("login", "Auth\LoginController@showLoginForm")->name("login");
Route::post("login", "Auth\LoginController@login");
Route::post("logout", "Auth\LoginController@logout")->name("logout");

// Cuenta
Route::get("cuenta", "UsuarioController@detalles")->name("cuenta.detalles");
Route::post("cuenta", "UsuarioController@modificar");
Route::get("cuenta/cambiar-password", "UsuarioController@formularioPassword")->name("cuenta.cambiar-password");
Route::post("cuenta/cambiar-password", "UsuarioController@cambiarPassword");

// Inicio
Route::get("/", "InicioController@index")->name("inicio");

// Choferes
Route::resource("choferes", "ChoferesController")->except(["edit"]);

// Proveedores
Route::resource("proveedores", "ProveedoresController")->except(["edit"]);

// Vehiculos
Route::resource("vehiculos", "VehiculosController")->except(["edit"]);
Route::get("vehiculos/{id}/registrar-kilometraje", "VehiculosController@formularioRegistrarKms")->name("vehiculos.registrar-kilometraje");
Route::post("vehiculos/{id}/registrar-kilometraje", "VehiculosController@registrarKms");

// Trabajos de vehiculos
Route::resource("trabajos-vehiculos", "TrabajosVehiculosController")->except(["edit", "destroy"]);

// Alquileres
Route::get("alquileres/registrar", "AlquileresController@create")->name("alquileres.create");
Route::resource("alquileres", "AlquileresController")->except(["create", "edit", "destroy"]);

Route::post("alquileres/{id}/terminar", "AlquileresController@terminar")->name("alquileres.terminar");
Route::get("alquileres/{id}/registrar-pago", "AlquileresController@formularioRegistrarPago")->name("alquileres.registrar-pago");
Route::post("alquileres/{id}/registrar-pago", "AlquileresController@registrarPago");

// Gastos adicionales
Route::resource("gastos-adicionales", "GastosAdicionalesController")->except(["edit", "destroy"]);

// Reportes
Route::get("reportes/balances", "ReportesController@mostrarBalances")->name("reportes.balances");
Route::get("reportes/vehiculos", "ReportesController@mostrarVehiculos")->name("reportes.vehiculos");
Route::get("reportes/choferes", "ReportesController@mostrarChoferes")->name("reportes.choferes");

resources/views/layouts/main.blade.php
<!doctype html>
<html lang="en">

<head>
	<title>@yield('title') - CarLend</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap/css/bootstrap.min.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/vendor/font-awesome/css/font-awesome.min.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/vendor/linearicons/style.css') }}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">
	<link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">
	@yield('custom-css')


	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="{{ asset('assets/img/apple-icon.png') }}">
	<link rel="icon" type="image/png" sizes="96x96" href="{{ asset('assets/img/favicon.png') }}">
</head>

<body>
	<!-- WRAPPER -->
	<div id="wrapper">

		<!-- NAVBAR -->
		@include('layouts.navbar')
		<!-- END NAVBAR -->
		
		<!-- LEFT SIDEBAR -->
		@include('layouts.nav-sidebar')

		<!-- END LEFT SIDEBAR -->
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->
			<div class="main-content">
				<div class="container-fluid">
					
					@yield('content')
					
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN -->

	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="{{ asset('assets/vendor/jquery/jquery.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap/js/bootstrap.min.js') }}"></script>
	<script src="{{ asset('assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
	<script src="{{ asset('assets/scripts/klorofil-common.js') }}"></script>
	@yield('custom-js')

</body>

</html>

resources/views/layouts/nav-sidebar.blade.php
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<li>
							<a href="{{ route('inicio') }}" {{ request()->is('/') ? "class=active" : "" }}><i class="lnr lnr-home"></i> <span>Inicio</span></a>
						</li>
						<li>
							<a href="{{ route('choferes.index') }}" {{ request()->is('choferes*') ? "class=active" : "" }}><i class="lnr lnr-user"></i> <span>Choferes</span></a>
						</li>
						<li>
							<a href="{{ route('proveedores.index') }}" {{ request()->is('proveedores*') ? "class=active" : "" }}><i class="lnr lnr-store"></i> <span>Proveedores</span></a>
						</li>
						<li>
							<a href="{{ route('vehiculos.index') }}" {{ request()->is('vehiculos*') ? "class=active" : "" }}><i class="lnr lnr-car"></i> <span>Vehículos</span></a>
						</li>
						<li>
							<a href="{{ route('trabajos-vehiculos.index') }}" {{ request()->is('trabajos-vehiculos*') ? "class=active" : "" }}><i class="fa fa-wrench" aria-hidden="true"></i> <span>Trabajos en vehiculos</span></a>
						</li>
						<li>
							<a href="{{ route('alquileres.index') }}" {{ request()->is('alquileres*') ? "class=active" : "" }}><i class="fa fa-handshake-o" aria-hidden="true" style="font-size: 15px"></i> <span>Alquileres</span></a>
						</li>
						<li>
							<a href="{{ route('gastos-adicionales.index') }}" {{ request()->is('gastos-adicionales*') ? "class=active" : "" }}><i class="fa fa-usd" aria-hidden="true" style="margin: 0 13px 0 5px;"></i> <span>Gastos adicionales</span></a>
						</li>
						<li>
							<a href="#subPages" data-toggle="collapse" class="collapsed {{ request()->is('reportes*') ? 'active' : '' }}"><i class="lnr lnr-chart-bars"></i> <span>Reportes</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
							<div id="subPages" class="collapse ">
								<ul class="nav">
									<li><a href="{{ route('reportes.balances') }}" class="">Balances</a></li>
									<li><a href="{{ route('reportes.vehiculos') }}" class="">Vehículos</a></li>
									<li><a href="{{ route('reportes.choferes') }}" class="">Choferes</a></li>
								</ul>
							</div>
						</li>
					</ul>
				</nav>
			</div>
		</div>

resources/views/layouts/navbar.blade.php
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="brand">
				<a href="{{ route('inicio') }}"><img src="{{ asset('assets/img/carlend-logo.png') }}" alt="Carlend Logo" class="img-responsive logo"></a>
			</div>
			<div class="container-fluid">
				<div class="navbar-btn">
					<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
				</div>
				<div id="navbar-menu">
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
								<i class="lnr lnr-alarm"></i>
								@if(sizeof($notificaciones) > 0)
								<span class="badge bg-danger">{{ sizeof($notificaciones) }}</span>
								@endif
							</a>
							<ul class="dropdown-menu notifications">
							

								@if(sizeof($notificaciones) > 0)

									@foreach($notificaciones as $notificacion)

										<li>
											<a href="{{ $notificacion->url }}" class="notification-item"><i class="{{ $notificacion->icono }}" style="color: {{ $notificacion->colorIcono  }};" aria-hidden="true"></i>{{ $notificacion->texto }}</a>
										</li>

									@endforeach

								@else
									<li><a href="javascript:void(0);" class="notification-item">No hay notificaciones o tareas pendientes</a></li>
								@endif
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span>{{ Auth::user()->name }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="{{ route('cuenta.detalles') }}"><i class="lnr lnr-user"></i> <span>Mi cuenta</span></a></li>
								<li>
									<a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
										<i class="lnr lnr-exit"></i> <span>Cerrar sesión</span>
									</a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>